CREATE SCHEMA IF NOT EXISTS %schemaName%;

CREATE TABLE IF NOT EXISTS %schemaName%.EVENT_STORE
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1),
    TYPE VARCHAR(255),
    CREATED TIME(4) WITHOUT TIME ZONE,
    PAYLOAD CLOB,
    PRIMARY KEY (ID)
);