CREATE SCHEMA IF NOT EXISTS %schemaName%;
SET SCHEMA %schemaName%;

CREATE TABLE IF NOT EXISTS OUTBOX_SCHEMA_VERSION(
        ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1),
        VERSION VARCHAR(255) NOT NULL,
        CREATED TIMESTAMP NOT NULL,
        PRIMARY KEY (ID)
);

INSERT INTO OUTBOX_SCHEMA_VERSION (VERSION, CREATED) VALUES ('0.0.1', CURRENT_TIMESTAMP);

CREATE IF NOT EXISTS EVENT_STORE
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1),
    TYPE VARCHAR(255),
    CREATED TIME(4) WITHOUT TIME ZONE,
    PAYLOAD BLOB,
    PRIMARY KEY (ID)
);
