CREATE SCHEMA IF NOT EXISTS %schemaName%;
SET SCHEMA %schemaName%;

CREATE IF NOT EXISTS EVENT_STORE
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1),
    TYPE VARCHAR(255),
    CREATED TIME(4) WITHOUT TIME ZONE,
    PAYLOAD BLOB,
    PRIMARY KEY (ID)
);
