-- this script updates the tables OUTBOX_SCHEMA_VERSION and event_store.
ALTER SESSION SET CURRENT_SCHEMA = %schemaName%;

INSERT INTO OUTBOX_SCHEMA_VERSION (VERSION, CREATED) VALUES ('1.0.0', CURRENT_TIMESTAMP);

ALTER TABLE EVENT_STORE
    ADD (tmpdetails  CLOB);

UPDATE EVENT_STORE SET tmpdetails=PAYLOAD;
COMMIT;

ALTER TABLE EVENT_STORE DROP COLUMN PAYLOAD;

ALTER TABLE EVENT_STORE
    RENAME COLUMN tmpdetails TO PAYLOAD;

ALTER TABLE EVENT_STORE ADD (REMAINING_RETRIES INT DEFAULT 5 NOT NULL,
    BLOCKED_UNTIL TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ERROR VARCHAR(1000),
    CAMUNDA_TASK_ID VARCHAR(40));


