CREATE SCHEMA IF NOT EXISTS TASKANA_TABLES;


CREATE TABLE TASKANA_TABLES.event_store
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    type VARCHAR(32) NOT NULL,
    created timestamp,
    payload VARCHAR(1024),
    CONSTRAINT event_store_pkey PRIMARY KEY (id)
);


CREATE TABLE TASKANA_TABLES.OUTBOX_SCHEMA_VERSION(
        ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        VERSION VARCHAR(255) NOT NULL,
        CREATED TIMESTAMP NOT NULL,
        PRIMARY KEY (ID)
);
INSERT INTO TASKANA_TABLES.OUTBOX_SCHEMA_VERSION (VERSION, CREATED) VALUES ('0.0.1', CURRENT_TIMESTAMP);


