-- ENGINE BPMN --
-- Dont clear ByteArray and procdef! --
DELETE FROM ACT_GE_PROPERTY;
DELETE FROM ACT_RU_JOB;
DELETE FROM ACT_RU_JOBDEF;
DELETE FROM ACT_RU_TASK;
DELETE FROM ACT_RU_VARIABLE;
DELETE FROM ACT_RU_EXECUTION;
DELETE FROM ACT_RU_EVENT_SUBSCR;
DELETE FROM ACT_RU_IDENTITYLINK;
DELETE FROM ACT_RU_EVENT_SUBSCR;
DELETE FROM ACT_RU_INCIDENT;
DELETE FROM ACT_RU_FILTER;
DELETE FROM ACT_RU_METER_LOG;
DELETE FROM ACT_RU_EXT_TASK;
DELETE FROM ACT_RU_BATCH;

--DMN--
DELETE FROM ACT_RE_DECISION_DEF;

--CMMN--
DELETE FROM ACT_RU_CASE_EXECUTION;
DELETE FROM ACT_RU_CASE_SENTRY_PART;
DELETE FROM ACT_RE_CASE_DEF;

--History--
DELETE FROM ACT_HI_OP_LOG;
DELETE FROM ACT_HI_DETAIL;
DELETE FROM ACT_HI_TASKINST;
DELETE FROM ACT_HI_VARINST;
DELETE FROM ACT_HI_JOB_LOG;
DELETE FROM ACT_HI_BATCH;
DELETE FROM ACT_HI_IDENTITYLINK;
DELETE FROM ACT_HI_PROCINST;
DELETE FROM ACT_HI_ACTINST;
DELETE FROM ACT_HI_INCIDENT;
DELETE FROM ACT_HI_COMMENT;
DELETE FROM ACT_HI_ATTACHMENT;
DELETE FROM ACT_HI_CASEINST;
DELETE FROM ACT_HI_CASEACTINST;
DELETE FROM ACT_HI_DECINST;
DELETE FROM ACT_HI_DEC_IN;
DELETE FROM ACT_HI_DEC_OUT;
