-- this script updates the tables OUTBOX_SCHEMA_VERSION and event_store.
ALTER SESSION SET CURRENT_SCHEMA = %schemaName%;

INSERT INTO OUTBOX_SCHEMA_VERSION (VERSION, CREATED) VALUES ('1.11.0', CURRENT_TIMESTAMP);

ALTER TABLE EVENT_STORE ADD (SYSTEM_ENGINE_IDENTIFIER VARCHAR(128) DEFAULT 'default');

