-- this script updates the tables OUTBOX_SCHEMA_VERSION and event_store.
SET search_path TO %schemaName%;

INSERT INTO OUTBOX_SCHEMA_VERSION (VERSION, CREATED) VALUES ('1.0.0', CURRENT_TIMESTAMP);

ALTER TABLE event_store ADD COLUMN REMAINING_RETRIES INT NOT NULL DEFAULT 5;
ALTER TABLE event_store ADD COLUMN BLOCKED_UNTIL TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ;
ALTER TABLE event_store ADD COLUMN ERROR VARCHAR(1000);
ALTER TABLE event_store ADD COLUMN CAMUNDA_TASK_ID VARCHAR(40);




